### PR TITLE
chore: add an optional route which is available along with service

### LINKED ISSUE #10: Demo a case when navigation target (route) is registered automatically when a service becomes available
Current demo uses `GreetService` if it's available.
It fallbacks to default message if there is no service.
We need a demo which register a route which uses the service once the service becomes available.
When service is deregistered the route should be deregsitered.

### PR DESCRIPTION
**Pull request by denis-anisimov**
fixes #10

### CODE REVIEW

**Comment by mstahv** [comment]
If the StaticResources  class is used, does the logo work at all anymore in the example?

**Comment by mstahv** [comment]
Not sure if the example is easier or harder now to understand when there is a common superclass? Even if there was some replication, the example views, I'd prefer to have those separately (easier for users to understand). The view new view that is shown based on availability of the service could even be simpler and just add a static page with greeting from the service (no input or button) 🤔 What do you think?

**Comment by denis-anisimov** [comment]
> If the StaticResources class is used, does the logo work at all anymore in the example?

`StaticResources` had at least wrong impl since there was a wildcard which prevents handling of generated resources by the VaadinServlet. It should have had only one direct path to the image.
But:
- no need since the image is served as a resource from the Jar path automatically.
- `StaticResources` adds a complexity: extra class which I'm not even sure allows PWA to work at all: PWA asks ServletContext for resources to generate other resources. I'm not sure that `StaticResources` allows to return a working URL for the static resources for the `ServletContext`  of the _registered_ servlet. It can be made working for sure but then a custom `ServletContextHelper`  class needs to be used and HTTP whiteboard `xxxx.select` property should be used for servlet registration and resource registration: then they use the same `ServletContext`  for sure.


I don't know whether the logo works since I don't know the intention.
I see some logo at least on the page: not sure whether it's the one or not.

**Comment by denis-anisimov** [comment]
> Not sure if the example is easier or harder now to understand when there is a common superclass? Even if there was some replication, the example views, I'd prefer to have those separately (easier for users to understand). The view new view that is shown based on availability of the service could even be simpler and just add a static page with greeting from the service (no input or button) 🤔 What do you think?

The page duplication doesn't look good for me as well: why would I want the same page?
But this project became already something which I don't like : it's not a starter anymore and this is rather a demo. I don't have abilities to make proper demos without exact specification what it should contain.

If you think the static page with the greeting service is better then I'm fine with this.

**Comment by mstahv** [comment]
Yup, the logo should be visible on top left corner in the app layout.

**Review by mstahv — APPROVED** [review]

**Pull request merged**
